const t = {
  common: {
    back: "Voltar",
    loading: "Carregando...",
    error: "Erro",
    success: "Sucesso",
    cancel: "Cancelar",
    confirm: "Confirmar",
    ok: "OK",
    or: "ou",
  },
  auth: {
    entry: {
      tagline: "Estilo e Tradição",
      access: "Acessar",
      googleLabel: "Continuar com Google",
      emailLogin: "Entrar com Email",
      noAccount: "Ainda não tem uma conta? ",
      createAccount: "Criar conta",
    },
    login: {
      title: "Acesse sua conta",
      subtitle: "Entre com suas credenciais para continuar",
      emailPlaceholder: "E-mail",
      passwordPlaceholder: "Senha",
      rememberMe: "Lembrar-me",
      forgotPassword: "Esqueceu sua senha?",
      submit: "Acessar",
      continueWith: "ou continue com",
      googleLabel: "Continuar com Google",
      noAccount: "Não tem conta? ",
      signupLink: "Cadastre-se",
      errorFillFields: "Informe suas credenciais",
      showPassword: "Mostrar senha",
      hidePassword: "Ocultar senha",
    },
    forgotPassword: {
      title: "Recuperar senha",
      subtitle:
        "Informe o e-mail da sua conta. Enviaremos um link para redefinir a senha.",
      emailPlaceholder: "E-mail",
      submit: "Enviar link",
      sentLabel: "E-mail enviado",
      backToLogin: "Voltar ao login",
      errorNoEmail: "Informe seu e-mail.",
      errorInvalidEmail: "Informe um e-mail válido.",
      successTitle: "Verifique seu e-mail",
      successMessage:
        "Se existir uma conta com esse endereço, você receberá as instruções em instantes.",
    },
    resetPassword: {
      title: "Nova senha",
      subtitle: "Defina uma nova senha para a sua conta.",
      passwordPlaceholder: "Nova senha",
      confirmPlaceholder: "Confirmar senha",
      submit: "Salvar senha",
      errorFillFields: "Preencha os dois campos.",
      errorMismatch: "As senhas não coincidem.",
      successTitle: "Senha atualizada",
      successMessage: "Você já pode usar a nova senha para entrar.",
      noSession:
        "Sessão inválida ou expirada. Solicite um novo link pelo login.",
    },
    signup: {
      title: "Crie sua conta",
      subtitle: "Preencha os dados abaixo para começar",
      namePlaceholder: "Nome (opcional)",
      emailPlaceholder: "E-mail",
      passwordPlaceholder: "Senha (mín. 6 caracteres)",
      submit: "Criar conta",
      hasAccount: "Já tem conta? ",
      loginLink: "Entrar",
      errorFillFields: "Informe suas credenciais",
      errorPasswordMin: (min: number) =>
        `Senha deve ter no mínimo ${min} caracteres.`,
      successTitle: "Conta criada",
      successMessage: "Confirme seu e-mail (se habilitado) ou faça login.",
    },
  },
  tabs: {
    home: "Início",
    explore: "Explorar",
    schedule: "Agendar",
    agenda: "Agenda",
    account: "Conta",
  },
  schedule: {
    title: "Finalizar Agendamento",
    pay: (amount: string) => `Pagar R$ ${amount}`,
    timeoutTitle: "Timeout",
    timeoutMessage:
      "A operação demorou demais. Verifique a conexão e tente novamente.",
    errorPaymentCode: "Não foi possível gerar o código de pagamento.",
    errorCheckout: "Erro ao inicializar checkout",
    cancelledOrError: "Pagamento cancelado ou erro",
    successTitle: "Sucesso!",
    successMessage: "Seu pagamento foi confirmado.",
    errorGeneric: "Ocorreu uma falha no processamento.",
  },
  account: {
    defaultName: "Usuário",
    logout: "Sair",
  },
  layout: {
    missingStripeKey: "Configure EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY no .env",
  },
} as const;

export default t;
