import { theme } from "@/constants/theme";
import { StyleSheet } from "react-native";

export const s = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  safeArea: {
    flex: 1,
  },
  mainColumn: {
    flex: 1,
    minHeight: 0,
  },
  header: {
    backgroundColor: theme.colors.background,
    overflow: "hidden",
  },
  raysWrap: {
    position: "absolute",
    top: 0,
    zIndex: 0,
    overflow: "hidden",
  },
  headerContent: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1,
  },
  tagline: {
    color: theme.colors.textLight,
    fontFamily: "Chivo_300Light",
    fontSize: 9,
    letterSpacing: 2.5,
    textTransform: "uppercase",
    marginTop: 10,
    opacity: 0.95,
  },
  body: {
    flex: 1,
    minHeight: 0,
    backgroundColor: theme.colors.authSheetFill,
    borderTopLeftRadius: theme.radius.authSheet,
    borderTopRightRadius: theme.radius.authSheet,
    overflow: "hidden",
  },
  bodyTopFade: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 56,
    borderTopLeftRadius: theme.radius.authSheet,
    borderTopRightRadius: theme.radius.authSheet,
    zIndex: 0,
  },
  bodyContent: {
    flex: 1,
    minHeight: 0,
    zIndex: 1,
    justifyContent: "flex-end",
  },
  scrollView: {
    flexShrink: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: theme.spacing.xxl,
    paddingTop: theme.spacing.xxxl,
  },
  title: {
    color: "#242428",
    fontWeight: "700",
    fontSize: 22,
    letterSpacing: -0.3,
    marginBottom: theme.spacing.sm,
  },
  subtitle: {
    color: "rgba(0, 0, 0, 0.48)",
    fontSize: 14,
    lineHeight: 20,
    marginBottom: theme.spacing.xxxl,
  },
  feedbackBanner: {
    borderRadius: theme.radius.md,
    padding: theme.spacing.lg,
    marginBottom: theme.spacing.xxl,
    borderWidth: 1,
  },
  feedbackSuccess: {
    backgroundColor: "rgba(254, 186, 67, 0.12)",
    borderColor: "rgba(254, 186, 67, 0.45)",
  },
  feedbackError: {
    backgroundColor: "rgba(200, 60, 60, 0.06)",
    borderColor: "rgba(200, 60, 60, 0.28)",
  },
  feedbackTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#242428",
    marginBottom: theme.spacing.sm,
  },
  feedbackBody: {
    fontSize: 14,
    lineHeight: 20,
    color: "rgba(0, 0, 0, 0.52)",
  },
  inputWrap: {
    backgroundColor: theme.colors.inputBg,
    borderWidth: 1,
    borderColor: theme.colors.inputBorder,
    borderRadius: theme.radius.md,
    marginBottom: theme.spacing.xxl,
    shadowColor: theme.colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  input: {
    padding: theme.spacing.lg,
    fontSize: 16,
    color: theme.colors.textPrimary,
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    minHeight: 52,
  },
  inputFlex: {
    flex: 1,
    paddingVertical: theme.spacing.lg,
    paddingLeft: theme.spacing.lg,
    paddingRight: theme.spacing.sm,
    fontSize: 16,
    color: theme.colors.textPrimary,
  },
  passwordToggle: {
    paddingVertical: theme.spacing.sm,
    paddingHorizontal: theme.spacing.md,
    marginRight: theme.spacing.sm,
    justifyContent: "center",
    alignItems: "center",
  },
  optionsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    // marginTop: 4,
    marginBottom: theme.spacing.xxxl,
  },
  checkRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.sm,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: theme.radius.sm,
    borderWidth: 1.5,
    borderColor: theme.colors.inputBorder,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.authSheetFill,
  },
  checkboxChecked: {
    backgroundColor: theme.colors.gold,
    borderColor: theme.colors.gold,
  },
  checkMark: {
    color: theme.colors.white,
    fontSize: 12,
    fontWeight: "700",
    // marginTop: -1,
  },
  optionLabel: {
    fontSize: 14,
    color: theme.colors.textMuted,
  },
  forgotText: {
    fontSize: 14,
    color: theme.colors.gold,
    fontWeight: "600",
  },
  backButton: {
    position: "absolute",
    left: theme.spacing.lg,
    zIndex: 2,
  },
  backButtonCard: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.11)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.22,
    shadowRadius: 8,
    elevation: 5,
  },
  stickyFooter: {
    paddingHorizontal: theme.spacing.xxl,
    paddingTop: theme.spacing.md,
    flexShrink: 0,
  },
  goldButton: {
    backgroundColor: theme.colors.gold,
    borderRadius: theme.radius.buttonLg,
    paddingVertical: 16,
    minHeight: 52,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: theme.spacing.sm,
    borderWidth: 1,
    borderColor: "rgba(254, 186, 67, 0.5)",
    shadowColor: theme.colors.goldShadow,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.32,
    shadowRadius: 14,
    elevation: 8,
  },
  goldButtonLoading: {
    opacity: 0.92,
  },
  goldButtonText: {
    color: theme.colors.white,
    fontSize: 16,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  dividerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
  },
  dividerLine: {
    flex: 1,
    height: StyleSheet.hairlineWidth,
    backgroundColor: "rgba(0, 0, 0, 0.08)",
  },
  dividerText: {
    marginHorizontal: theme.spacing.lg,
    color: "rgba(0, 0, 0, 0.38)",
    fontSize: 13,
    fontWeight: "500",
  },
  googleButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: theme.radius.buttonLg,
    borderWidth: 1,
    borderColor: "rgba(0, 0, 0, 0.08)",
    paddingVertical: theme.spacing.lg,
    backgroundColor: theme.colors.white,
    gap: theme.spacing.md,
  },
  googleLabel: {
    fontSize: 14,
    color: theme.colors.textPrimary,
    fontWeight: "400",
  },
  signupLink: {
    fontSize: 14,
    color: theme.colors.textSecondary,
  },
  signupLinkWrap: {
    marginTop: theme.spacing.xxl,
    alignItems: "center",
  },
  signupLinkHighlight: {
    color: theme.colors.gold,
    fontWeight: "700",
  },
  loadingIndicator: {
    marginVertical: theme.spacing.xxl,
  },
  oauthSpinner: {
    width: 24,
    height: 24,
  },
  buttonDisabled: {
    opacity: 0.55,
  },
  pressed: {
    opacity: 0.9,
    transform: [{ scale: 0.98 }],
  },
  pressedLight: {
    opacity: 0.85,
  },
});
